# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    desc "Runs all the tests"
  lane :test do
    scan(scheme: "gitswift",code_coverage: true, device: "iPhone 6s")
    slather(
      output_directory: "coverage",
      workspace: "gitswift.xcworkspace",
      scheme: "gitswift",
      proj: "gitswift.xcodeproj",
      html: true,
    
    )
  end
end
